---

- name: Create the application user
  user: name={{ gunicorn_user }} state=present

- name: Create the application group
  group: name={{ gunicorn_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ gunicorn_user }} group={{ gunicorn_group }} state=present

- name: Ensure that the $HOME/.ssh file permissions are set properly
  file: path=/home/{{ gunicorn_user }}/.ssh
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0700
        state=directory

- name: Add ssh private key
  copy: src=".ssh/{{ gunicorn_user }}_id_rsa" dest=/home/{{ gunicorn_user }}/.ssh/id_rsa
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0600

- name: Add ssh public key
  copy: src=".ssh/{{ gunicorn_user }}_id_rsa.pub" dest=/home/{{ gunicorn_user }}/.ssh/id_rsa.pub
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0600

