---
- name: Update the apt cache
  apt: update-cache=yes

- name: Upgrade all packages
  apt: upgrade=yes

- name: Upgrade dist
  apt: upgrade=dist

- name: Install common software
  apt: name={{item}} state=present
  with_items:
    - software-properties-common
    - console-data 
    - unicode-data 
    - language-pack-fr-base
    - language-pack-fr
    - htop
    - dfc  
    - strace
    - make
    - gcc
    - lsof
    - vim
    - curl
    - git
    - mc
    - sysstat
    - iotop
    - dstat
    - iptraf
    - tmux
    - zsh

- name: Set hostname
  hostname: name={{common_hostname}}

- name: Update hosts - add hostname to /etc/hosts
  lineinfile: 'line="127.0.0.1 {{common_hostname}}" dest=/etc/hosts state=present'

- name: set locale to fr_FR.UTF-8
  command: /usr/sbin/update-locale LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8

- name: Set timezone variables
  copy: content={{common_timezone}} dest=/etc/timezone owner=root group=root mode=0644 backup=yes
  notify:
    - update timezone

- name: Allow sudo without password
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo\s+ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
